[env]
NGINX_BASE = "nginx"
NGINX_VER = "1.13.5"
# duplicating NGINX_VER because of limitation with cargo_make
NGINX_MODULES = "--with-compat  --with-threads --with-http_addition_module --with-stream"
DOCKER_TOOL="docker run -it --rm -v ${ROOT_DIR}:/src -w /src/${MODULE_PROJ_NAME} ${RUST_TOOL}"

[tasks.set-env]
env = { "NGX_OPT" = "", "NGINX_SRC" = "nginx-darwin" , "TOOL"=""}

[tasks.set-env.linux]
env = { "NGX_OPT" = """--with-file-aio --with-http_ssl_module --with-stream_ssl_module\
      --with-cc-opt='-g -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' \
     --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'
   """,  "NGINX_SRC" = "nginx-linux", "TOOL"="" }

[tasks.super_clean]
command = "rm"
args = ["-rf","nginx"]

[tasks.setup-nginx]
script = [
    "mkdir -p ${NGINX_BASE}"
]

[tasks.nginx-source]
descrption = "download nginx source code"
dependencies = ["set-env", "setup-nginx"]
script = [
    "rm -rf ${NGINX_BASE}/${NGINX_SRC}",
    "wget http://nginx.org/download/nginx-${NGINX_VER}.tar.gz",
    "tar zxf nginx-${NGINX_VER}.tar.gz",
    "mv nginx-${NGINX_VER} ${NGINX_SRC}",
    "mv ${NGINX_SRC} nginx",
    "rm nginx-${NGINX_VER}.tar.gz*"
]



[tasks.nginx-configure]
dependencies = ["set-env"]
script = [
   "cd ${CARGO_MAKE_WORKING_DIRECTORY}/${NGINX_BASE}/${NGINX_SRC}; ./configure --add-dynamic-module=../../module ${NGINX_MODULES}  ${NGX_OPT}"
]

[tasks.nginx-module]
dependencies = ["set-env"]
script = [
   "cd ${CARGO_MAKE_WORKING_DIRECTORY}/${NGINX_BASE}/${NGINX_SRC}; make modules"
]


[tasks.nginx-setup]
dependencies = ["nginx-source", "nginx-configure"]